openapi: 3.0.0
info:
  title: FitSync API
  version: 1.0.0
  description: API for tracking and retrieving user wellness data.
tags:
  - name: Users
    description: Operations about users
  - name: Sleep
    description: User sleep data operations
  - name: Wellness
    description: User wellness data operations (e.g., skin temperature)

paths:
  /sleep:
    get:
      tags:
        - Sleep
      summary: Get all sleep logs
      description: Retrieves a list of all sleep logs from all users.
      responses:
        "200":
          description: A list of all sleep logs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/SleepLog"
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users:
    get:
      tags:
        - Users
      summary: Get all users
      description: Retrieves a list of all users.
      responses:
        "200":
          description: A list of all users.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/demo:
    get:
      tags:
        - Users
      summary: Get the demo user
      description: Retrieves a specific hardcoded demo user.
      responses:
        "200":
          description: The demo user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: "#/components/schemas/User"
        "404":
          description: Demo user not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{email}:
    get:
      tags:
        - Users
      summary: Get a user by email
      parameters:
        - name: email
          in: path
          required: true
          description: Email of the user to retrieve.
          schema:
            type: string
            format: email
      responses:
        "200":
          description: The requested user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: "#/components/schemas/User"
        "400":
          description: Bad Request. The email parameter is missing.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: User with the specified email not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{userId}/sleep:
    get:
      tags:
        - Sleep
      summary: Get all sleep logs for a user
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
      responses:
        "200":
          description: A list of sleep logs for the specified user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/SleepLog"
        "400":
          description: Bad Request. The userId parameter is missing.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{userId}/sleep/recent:
    get:
      tags:
        - Sleep
      summary: Get a user's most recent sleep log
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
      responses:
        "200":
          description: The most recent sleep log.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: "#/components/schemas/SleepLog"
        "400":
          description: Bad Request. The userId parameter is missing.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: No sleep logs found for this user.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{userId}/sleep/{date}:
    get:
      tags:
        - Sleep
      summary: Get a sleep log by date
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
        - name: date
          in: path
          required: true
          description: The date of the log (YYYY-MM-DD).
          schema:
            type: string
            format: date
      responses:
        "200":
          description: The requested sleep log.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: "#/components/schemas/SleepLog"
        "400":
          description: Bad Request. Required parameters are missing or invalid.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: No sleep log found for the specified date.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{userId}/temperature:
    get:
      tags:
        - Wellness
      summary: Get all skin temperature logs for a user
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
      responses:
        "200":
          description: A list of skin temperature logs for the user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/SkinTempLog"
        "400":
          description: Bad Request. The userId parameter is missing.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{userId}/temperature/{date}:
    get:
      tags:
        - Wellness
      summary: Get a skin temperature log by date
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
        - name: date
          in: path
          required: true
          description: The date of the log (YYYY-MM-DD).
          schema:
            type: string
            format: date
      responses:
        "200":
          description: The requested skin temperature log.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: "#/components/schemas/SkinTempLog"
        "400":
          description: Bad Request. Parameters are missing or invalid.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: No log found for the specified date.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /users/{userId}/breathing-rate/{date}:
    get:
      tags:
        - Wellness
      summary: Get a breathing rate log by date
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
        - name: date
          in: path
          required: true
          description: The date of the log (YYYY-MM-DD).
          schema:
            type: string
            format: date
      responses:
        "200":
          description: The requested breathing rate log.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    $ref: "#/components/schemas/BreathingRateLog"
        "400":
          description: Bad Request. Parameters are missing or invalid.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: No log found for the specified date.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "clv27x0850000rqw88plp8s6m"
        email:
          type: string
          format: email
          example: "mo.sleep@fitsync.com"
        firstName:
          type: string
          example: "Mo"
        lastName:
          type: string
          example: "Sleep"

    SleepLog:
      type: object
      properties:
        id:
          type: string
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        dateOfSleep:
          type: string
          format: date
          example: "2025-08-30"
        sleepScore:
          type: integer
          example: 85
        totalTimeInBed:
          type: integer
          description: Total time in bed in seconds.
          example: 28800
        sleepQuality:
          type: string
          example: "Good"

    SkinTempLog:
      type: object
      properties:
        id:
          type: string
          example: "c1f7a4a9-8f0c-4a3d-9c3a-3e7b1d9c1b3a"
        dateTime:
          type: string
          format: date-time
          example: "2025-08-30T04:00:00.000Z"
        nightlyRelative:
          type: number
          format: float
          description: Skin temperature variation from baseline.
          example: 1.2
        logType:
          type: string
          enum: [DEDICATED_TRACKER, OTHER]
          example: DEDICATED_TRACKER

    BreathingRateLog:
      type: object
      properties:
        id:
          type: string
          example: "d1e8b5b0-9a1d-5b4e-8d4b-4f8c2e0d2c4b"
        dateTime:
          type: string
          format: date-time
          example: "2025-08-30T04:15:00.000Z"
        breathingRateValue:
          type: number
          format: float
          description: Breaths per minute.
          example: 14.5

    Error:
      type: object
      properties:
        code:
          type: string
          example: "NOT_FOUND"
        message:
          type: string
          example: "Resource not found."

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          example: false
        error:
          $ref: "#/components/schemas/Error"
