openapi: 3.0.0
info:
  title: Fitness Dashboard API
  version: 1.0.0
  description: API for fitness data
paths:
  /sleep/logs:
    get:
      summary: Get all sleep logs.
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
  /sleep/recent:
    get:
      summary: Get the most recent sleep log for the specified user.
      parameters:
        - name: userId
          in: query
          required: true
          description: ID of the user to retrieve the recent sleep log for.
          schema:
            type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
  /users/all:
    get:
      summary: Get all users in the database.
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
  /users/demo:
    get:
      summary: Get the demo user.
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
