openapi: 3.0.0
info:
  title: FitSync API
  version: 1.0.0
  description: API for tracking and retrieving user wellness data.
paths:
  /sleep:
    get:
      summary: Get all sleep logs
      description: Retrieves a list of all sleep logs from all users.
      responses:
        "200":
          description: A list of all sleep logs.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sleepLogs:
                    type: array
                    items:
                      $ref: "#/components/schemas/SleepLog"
        "500":
          description: Internal Server Error.

  /users:
    get:
      summary: Get all users
      description: Retrieves a list of all users.
      responses:
        "200":
          description: A list of all users.
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
        "500":
          description: Internal Server Error.

  /users/demo:
    get:
      summary: Get the demo user
      description: Retrieves a specific hardcoded demo user.
      responses:
        "200":
          description: The demo user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: "#/components/schemas/User"
        "404":
          description: Demo user not found.
        "500":
          description: Internal Server Error.

  /users/email/{email}:
    get:
      summary: Get a user by email
      parameters:
        - name: email
          in: path
          required: true
          description: Email of the user to retrieve.
          schema:
            type: string
            format: email
      responses:
        "200":
          description: The requested user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  user:
                    $ref: "#/components/schemas/User"
        "400":
          description: Bad Request. The email parameter is missing.
        "404":
          description: User with the specified email not found.
        "500":
          description: Internal Server Error.

  /users/{userId}/sleep:
    get:
      summary: Get all sleep logs for a user
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
      responses:
        "200":
          description: A list of sleep logs for the specified user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sleepLogs:
                    type: array
                    items:
                      $ref: "#/components/schemas/SleepLog"
        "400":
          description: Bad Request. The userId parameter is missing.
        "500":
          description: Internal Server Error.

  /users/{userId}/sleep/recent:
    get:
      summary: Get a user's most recent sleep log
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
      responses:
        "200":
          description: The most recent sleep log.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sleepLog:
                    $ref: "#/components/schemas/SleepLog"
        "400":
          description: Bad Request. The userId parameter is missing.
        "404":
          description: No sleep logs found for this user.
        "500":
          description: Internal Server Error.

  /users/{userId}/sleep/{date}:
    get:
      summary: Get a sleep log by date
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
        - name: date
          in: path
          required: true
          description: The date of the log (YYYY-MM-DD).
          schema:
            type: string
            format: date
      responses:
        "200":
          description: The requested sleep log.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sleepLog:
                    $ref: "#/components/schemas/SleepLog"
        "400":
          description: Bad Request. Required parameters are missing or invalid.
        "404":
          description: No sleep log found for the specified date.
        "500":
          description: Internal Server Error.

  /users/{userId}/temperature:
    get:
      summary: Get all skin temperature logs for a user
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
      responses:
        "200":
          description: A list of skin temperature logs for the user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  logs:
                    type: array
                    items:
                      $ref: "#/components/schemas/SkinTempLog"
        "400":
          description: Bad Request. The userId parameter is missing.
        "500":
          description: Internal Server Error.

  /users/{userId}/temperature/{date}:
    get:
      summary: Get a skin temperature log by date
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user.
          schema:
            type: string
        - name: date
          in: path
          required: true
          description: The date of the log (YYYY-MM-DD).
          schema:
            type: string
            format: date
      responses:
        "200":
          description: The requested skin temperature log.
          content:
            application/json:
              schema:
                type: object
                properties:
                  log:
                    $ref: "#/components/schemas/SkinTempLog"
        "400":
          description: Bad Request. Parameters are missing or invalid.
        "404":
          description: No log found for the specified date.
        "500":
          description: Internal Server Error.

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
          example: "clv27x0850000rqw88plp8s6m"
        email:
          type: string
          format: email
          example: "mo.sleep@fitsync.com"
        firstName:
          type: string
          example: "Mo"
        lastName:
          type: string
          example: "Sleep"

    SleepLog:
      type: object
      properties:
        id:
          type: string
          example: "a1b2c3d4-e5f6-7890-1234-567890abcdef"
        dateOfSleep:
          type: string
          format: date
          example: "2025-08-30"
        sleepScore:
          type: integer
          example: 85
        totalTimeInBed:
          type: integer
          description: Total time in bed in seconds.
          example: 28800
        sleepQuality:
          type: string
          example: "Good"

    SkinTempLog:
      type: object
      properties:
        id:
          type: string
          example: "c1f7a4a9-8f0c-4a3d-9c3a-3e7b1d9c1b3a"
        dateTime:
          type: string
          format: date-time
          example: "2025-08-30T04:00:00.000Z"
        nightlyRelative:
          type: number
          format: float
          description: Skin temperature variation from baseline.
          example: 1.2
        logType:
          type: string
          enum: [DEDICATED_TRACKER, OTHER]
          example: DEDICATED_TRACKER
