openapi: 3.0.0
info:
  title: Fitness Dashboard API
  version: 1.0.0
  description: API for fitness data
paths:
  /sleep/all:
    get:
      summary: Get all sleep logs.
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
  /sleep/user:
    get:
      summary: Get all sleep logs for a specified user.
      parameters:
        - name: userEmail
          in: query
          required: true
          description: Email address of the user.
          schema:
            type: string
    responses:
      "200":
        description: A successful response.
        content:
          application/json:
            schema:
              type: object
  /users/all:
    get:
      summary: Get all users in the database.
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
  /users/get:
    get:
      summary: Get a user by email.
      parameters:
        - name: userEmail
          in: query
          required: true
          description: Email address of the user.
          schema:
            type: string
      responses:
        "200":
          description: A successful response.
          content:
            application/json:
              schema:
                type: object
